name: CI
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions: {}

jobs:
  python:
    name: 🐍
    uses: rotmanjanez/workflows/.github/workflows/reusable-python-ci.yml@f5e6fab21fa10913441d9c1c87510f5ee705c85b # feat/python-version-matrix
    with:
      enable-ty: true
      enable-mypy: false
    secrets: inherit
    permissions:
      contents: read
      id-token: write
